version: '2'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-app
    restart: always
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini

  #Nginx Service
  webserver:
    image: nginx:alpine
    restart: always
    tty: true
    ports:
      - "8082:80"
      - "445:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d

  #MySQL Service
  db:
    image: mysql:5.7.22
    restart: always
    tty: true
    ports:
      - "3000:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8091:80
    links:
      - db
    environment:
      PMA_HOST: ${PMA_HOST}

volumes:
  dbdata:
    driver: local
